format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$java\
$gradle\
$aws\
$custom\
$line_break\
$container\
$character"""

[git_status]
format = '([\[$ahead_behind\]]($style) )'
# show counts in addition to the arrows
ahead = '↑${count}'
diverged = '⇕↑${ahead_count}↓${behind_count}'
behind = '↓${count}'

[java]
style = '#876558' # default is 'red dimmed'
detect_folders = ['eManagement']
